version: "3.3"

services:
  oes-web:
    image: node:16
    volumes:
      - ./:/code
    working_dir: /code
    command: bash -c "yarn && yarn dev"

  vcn-web:
    image: node:16
    command: 'bash -c "yarn && yarn dev"'
    volumes:
      - ./vcn-web:/vcn-web
    working_dir: /vcn-web
    networks:
      - back-tier
    ports:
      - "3000:3000"

  nginx:
    networks:
      - back-tier
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./vcn-web:/vcn-web
      - ./nginx/dev/default.conf:/etc/nginx/conf.d/default.conf

networks:
  back-tier:
    driver: bridge
