version: "3.3"

services:
  oes-web:
    image: node:16
    volumes:
      - ./:/code
    working_dir: /code
    command: bash -c "yarn && yarn dev"
  oes-pkg:
    volumes:
      - .:/code
    working_dir: /code
    build: .

networks:
  back-tier:
    driver: bridge
