version: "3.3"

services:
  oes-web:
    image: node:16
    volumes:
      - ./:/code
    working_dir: /code
    command: bash -c "yarn && yarn dev"
  oes-pkg:
    volumes:
      - .:/code
    working_dir: /code
    build: .
  vcn-web:
    image: node:16
    volumes:
      - ./provider-messaging/:/code
    working_dir: /code
    command: bash -c "yarn && yarn dev"
    environment:
      - VITE_CEREBRO_URL=http://localhost:8426/api
    ports:
      - "3500:3500"

networks:
  back-tier:
    driver: bridge
