version: "3.3"

services:
  oes-web:
    image: node:16
    volumes:
      - ./:/code
    working_dir: /code
  oes-test:
    image: cypress/included:8.0.0
    volumes:
      - ./:/code
    working_dir: /code

networks:
  back-tier:
    driver: bridge
